/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipperDraftRouteImport } from './routes/shipper-draft'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FinancialAppsRouteImport } from './routes/financial-apps'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as GuidesArticleIdRouteImport } from './routes/guides/$articleId'
import { Route as CalculatorsCalcIdRouteImport } from './routes/calculators/$calcId'

const ShipperDraftRoute = ShipperDraftRouteImport.update({
  id: '/shipper-draft',
  path: '/shipper-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialAppsRoute = FinancialAppsRouteImport.update({
  id: '/financial-apps',
  path: '/financial-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesArticleIdRoute = GuidesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => GuidesRoute,
} as any)
const CalculatorsCalcIdRoute = CalculatorsCalcIdRouteImport.update({
  id: '/$calcId',
  path: '/$calcId',
  getParentRoute: () => CalculatorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/financial-apps': typeof FinancialAppsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/investing': typeof InvestingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipper-draft': typeof ShipperDraftRoute
  '/calculators/$calcId': typeof CalculatorsCalcIdRoute
  '/guides/$articleId': typeof GuidesArticleIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/financial-apps': typeof FinancialAppsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/investing': typeof InvestingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipper-draft': typeof ShipperDraftRoute
  '/calculators/$calcId': typeof CalculatorsCalcIdRoute
  '/guides/$articleId': typeof GuidesArticleIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/faq': typeof FaqRoute
  '/financial-apps': typeof FinancialAppsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/investing': typeof InvestingRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/shipper-draft': typeof ShipperDraftRoute
  '/calculators/$calcId': typeof CalculatorsCalcIdRoute
  '/guides/$articleId': typeof GuidesArticleIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bank-accounts'
    | '/calculators'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/financial-apps'
    | '/guides'
    | '/investing'
    | '/privacy'
    | '/reviews'
    | '/shipper-draft'
    | '/calculators/$calcId'
    | '/guides/$articleId'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bank-accounts'
    | '/calculators'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/financial-apps'
    | '/guides'
    | '/investing'
    | '/privacy'
    | '/reviews'
    | '/shipper-draft'
    | '/calculators/$calcId'
    | '/guides/$articleId'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bank-accounts'
    | '/calculators'
    | '/contact'
    | '/disclosure'
    | '/faq'
    | '/financial-apps'
    | '/guides'
    | '/investing'
    | '/privacy'
    | '/reviews'
    | '/shipper-draft'
    | '/calculators/$calcId'
    | '/guides/$articleId'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BankAccountsRoute: typeof BankAccountsRoute
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  FaqRoute: typeof FaqRoute
  FinancialAppsRoute: typeof FinancialAppsRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  InvestingRoute: typeof InvestingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  ShipperDraftRoute: typeof ShipperDraftRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipper-draft': {
      id: '/shipper-draft'
      path: '/shipper-draft'
      fullPath: '/shipper-draft'
      preLoaderRoute: typeof ShipperDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-apps': {
      id: '/financial-apps'
      path: '/financial-apps'
      fullPath: '/financial-apps'
      preLoaderRoute: typeof FinancialAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$articleId': {
      id: '/guides/$articleId'
      path: '/$articleId'
      fullPath: '/guides/$articleId'
      preLoaderRoute: typeof GuidesArticleIdRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/calculators/$calcId': {
      id: '/calculators/$calcId'
      path: '/$calcId'
      fullPath: '/calculators/$calcId'
      preLoaderRoute: typeof CalculatorsCalcIdRouteImport
      parentRoute: typeof CalculatorsRoute
    }
  }
}

interface CalculatorsRouteChildren {
  CalculatorsCalcIdRoute: typeof CalculatorsCalcIdRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsCalcIdRoute: CalculatorsCalcIdRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

interface GuidesRouteChildren {
  GuidesArticleIdRoute: typeof GuidesArticleIdRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesArticleIdRoute: GuidesArticleIdRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BankAccountsRoute: BankAccountsRoute,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  FaqRoute: FaqRoute,
  FinancialAppsRoute: FinancialAppsRoute,
  GuidesRoute: GuidesRouteWithChildren,
  InvestingRoute: InvestingRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  ShipperDraftRoute: ShipperDraftRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
